title:              Blog & CV
email:              deutanshin@gmail.com
description:        Visual Computing and Learning
author:             Donju Shin
baseurl:            ""
url:                "https://deutanshin.github.io"

# Social Profiles
twitter_username:   
github_username:    deutanshin
facebook_username: 
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Comment settings (Utterances)
utterances:
  repo: deutanshin/deutanshin.github.io
  issue_term: pathname # map post to issue by url path
  theme: github-light

# Build settings
markdown:           kramdown
kramdown:
  math_engine: mathjax
  mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
